config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, only: [:show]
  resources :transactions

  scope '/dashboard' do
    get '', to: 'dashboard#home'
    get '/upgrade', to: 'dashboard#upgrade_page'
    get '/upgrade_check', to: 'dashboard#upgrade_check'
    get '/pay', to: 'dashboard#upgrade_pay'
    post '/upgrade', to: 'dashboard#upgrade'
    get '/get_tutor', to: 'dashboard#be_my_tutor'
    post '/get_tutor', to: 'dashboard#assign_tutor'
    get 'social', to: 'dashboard#social'
    get '/test', to: 'dashboard#testing'
  end

  get 'tutorial', to: 'static#tutorial'
  get 'coupon',to: 'static#unavailable' # to: "static#coupon"
  get 'unavailable', to: 'static#unavailable'
  get 'how', to: 'static#how'
  root 'static#welcome'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
	def index
		@user = current_user
		client = Rails.configuration.coinbase
		account = client.account("383b7c1e-0381-5a2c-9e54-d716236d87e0")
		@addresses = account.addresses
		@adrs = @user.addresses
	end

	def show
		@address = Address.find(params[:id])
		if @address.user != current_user
			flash[:error] = "無法查看。"
			redirect_to controller: 'dashboard',action: 'home'
		end
		# # rake task will handle it
		# # check if payment have payed.
		# # coinbase
		# coinbase = Rails.configuration.coinbase
		# account_id = '383b7c1e-0381-5a2c-9e54-d716236d87e0'
		# account = coinbase.account(account_id)
		# # get address from coinbase account
		# adr = account.address(@address.address_id)

		# # check every transaction from address
		# btc_recieved = 0.0
		# adr.transactions.each do |tran|
		# 	# todo: check if btc payment is comfirm
		# 	# check if there is new income
		# 	btc_recieved += tran['amount']['amount'].to_f
		# 	if btc_recieved > @address.btc_recieved
		# 		# update btc_recieved
		# 		@address.btc_recieved = btc_recieved
		# 		# if finish paying
		# 		if @address.btc_recieved >= @address.btc_amount
		# 			@address.status = 'complete'
		# 			@address.notice = true
		# 		end
		# 	end
		# 	@address.save
		# end

		# # rake task will handle it
		# # price update
		# if @address.status == 'waiting' && Time.now > @address.btc_amount_expired
		# 	# get price
		# 	@resp = HTTParty.get("https://blockchain.info/ticker")
		# 	@USDbit = @resp["USD"]["15m"]
		# 	@TWDbit = @resp["TWD"]["15m"]
		# 	# update new btc amount
		# 	@address.btc_amount = (@address.twd_amount/@TWDbit).round(8)
		# 	@address.btc_amount_expired = Time.now + 15 * 60
		# 	@address.save
		# end
	end

	def new
		@transaction = Transaction.new
	end

	def create
		@transaction = Transaction.new
	end

	def edit
		@transaction = Transaction.find(params[:id])
	end

	def update
		@transaction = Transaction.find(params[:id])
	end

	def destroy
		@transaction = Transaction.find(params[:id])
	end
	private
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/index.html.haml
.inner
	- @adrs.all.each do |adr|
		日期: #{adr.created_at}
		%br/
		描述: #{adr.usage}
		%br/
		金額: #{adr.twd_amount}
		%br/
		幣值: #{adr.btc_amount}
		%br/
		已收到: #{adr.btc_recieved}
		%br/
		狀態: #{adr.status}
		%br/
		%br/
		=link_to '詳細資料', transaction_path(adr), class: 'button button-default'
		%br/
		%hr/
/ .inner
/ 	-if Rails.env.development?
/ 		%h2 All transaction
/ 		- @addresses.each do |adr|
/ 			%hr/
/ 			address: #{adr.address}
/ 			%br/
/ 			- adr.transactions.each do |transaction|
/ 				ID: #{transaction['id']}
/ 				%br/
/ 				Type: #{transaction['type']}
/ 				%br/
/ 				status: #{transaction['status']}
/ 				%br/
/ 				amount: #{transaction['amount']['amount']}-#{transaction['amount']['currency']}
/ 				%br/

app/views/transactions/show.html.haml
.inner#tran

	%img{:src => "https://chart.googleapis.com/chart?chs=250x250&cht=qr&chl=#{@address.address}?amount=#{@address.btc_amount}", :alt => ""}/
	%br/
	%h3.slim
		#{@address.address}
	- if @address.status == 'complete'
		已收到: #{@address.btc_recieved}btc
		%br/
		%br/
		%h3 付款已完成。
		%br/


	- elsif @address.status == 'waiting'
		- if (@address.btc_pending + @address.btc_recieved) == @address.btc_amount
			%h3 已收到比特幣，升級正在審核中..
		- else
			升級金額: #{@address.btc_amount}
			%br/
			已收到: #{@address.btc_pending+@address.btc_recieved}btc (請靜待系統更新)
			%br/
			請再發送 #{@address.btc_amount-(@address.btc_pending+@address.btc_recieved)} 比特幣到上面地址。
			%br/



	=link_to '回到主控台', '/dashboard', class: 'button button-default'